language: java
script: mvn package
deploy:
  provider: script
  skip_cleanup: true
  script: heroku auth:token &&
          heroku container:login --app ${HEROKU_APP} &&
          heroku container:push web &&
          heroku container:release web
  on:
    branch: master